version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      playwright:
        patterns:
          - '@playwright/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      lint-format:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
          - 'prettier-*'
          - 'typescript-eslint'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
